version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GYAEC4QW05043H3CNT681GAY:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GYAEC4QW05043H3CNT681GAY --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYAEC4QW05043H3CNT681GAY/input_ethnicity.csv.gz


  generate_study_population_01GYAEC4QW05043H3CNT681GAY:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="1"
      --param time_ever="False"
      --param time_scale="weeks"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age,imd,region,ethnicity"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GYAEC4QW05043H3CNT681GAY
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYAEC4QW05043H3CNT681GAY/input_*.csv.gz

  join_cohorts_01GYAEC4QW05043H3CNT681GAY:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GYAEC4QW05043H3CNT681GAY/input_20*.csv.gz
        --rhs output/01GYAEC4QW05043H3CNT681GAY/input_ethnicity.csv.gz
        --output-dir output/01GYAEC4QW05043H3CNT681GAY/joined
    needs: [generate_study_population_01GYAEC4QW05043H3CNT681GAY, generate_study_population_ethnicity_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      highly_sensitive:
        cohort: output/01GYAEC4QW05043H3CNT681GAY/joined/input_20*.csv.gz

  generate_measures_01GYAEC4QW05043H3CNT681GAY:
    run: >
      python:latest -m analysis.measures
        --breakdowns="sex,age,imd,region,ethnicity"
        --input_dir="output/01GYAEC4QW05043H3CNT681GAY/joined"

    needs: [join_cohorts_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      moderately_sensitive:
        measure: output/01GYAEC4QW05043H3CNT681GAY/joined/measure_all.csv
        decile_measure: output/01GYAEC4QW05043H3CNT681GAY/joined/measure_practice_rate_deciles.csv

  top_5_table_01GYAEC4QW05043H3CNT681GAY:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GYAEC4QW05043H3CNT681GAY"
    needs: [generate_measures_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      moderately_sensitive:
        tables: output/01GYAEC4QW05043H3CNT681GAY/joined/top_5*.csv

  plot_measure_01GYAEC4QW05043H3CNT681GAY:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns="sex,age,imd,region,ethnicity"
        --output-dir output/01GYAEC4QW05043H3CNT681GAY
    needs: [generate_measures_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      moderately_sensitive:
        measure: output/01GYAEC4QW05043H3CNT681GAY/plot_measure*.png
        deciles: output/01GYAEC4QW05043H3CNT681GAY/deciles_chart.png

  event_counts_01GYAEC4QW05043H3CNT681GAY:
    run: >
      python:latest python analysis/event_counts.py --input_dir="output/01GYAEC4QW05043H3CNT681GAY/joined" --output_dir="output/01GYAEC4QW05043H3CNT681GAY"
    needs: [join_cohorts_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      moderately_sensitive:
        measure: output/01GYAEC4QW05043H3CNT681GAY/event_counts.json

  generate_report_01GYAEC4QW05043H3CNT681GAY:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GYAEC4QW05043H3CNT681GAY"
      --population="adults"
      --breakdowns="sex,age,imd,region,ethnicity"
      --codelist-1-name="Doxycycline (tetracyclines)"
      --codelist-2-name="COPD Rescue Packs"
      --codelist-1-link="user/alexorlek/doxycycline-tetracyclines/4458c45a"
      --codelist-2-link="user/brian-mackenna/copd-rescue-packs/05fe3d58"
      --time-value="1"
      --time-scale="weeks"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
    needs: [event_counts_01GYAEC4QW05043H3CNT681GAY, top_5_table_01GYAEC4QW05043H3CNT681GAY, plot_measure_01GYAEC4QW05043H3CNT681GAY]
    outputs:
      moderately_sensitive:
        notebook: output/01GYAEC4QW05043H3CNT681GAY/report.html