version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01HW38MAP18PWK35KP7T46DST1:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --output-dir output/01HW38MAP18PWK35KP7T46DST1 --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01HW38MAP18PWK35KP7T46DST1/input_ethnicity.feather

  generate_study_population_weekly_01HW38MAP18PWK35KP7T46DST1:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_frequency="weekly"
      --param breakdowns=""
      --index-date_range="2024-04-01 to 2024-04-01 by week"
      --output-dir=output/01HW38MAP18PWK35KP7T46DST1
      --output-format=feather
      --output-file=output/01HW38MAP18PWK35KP7T46DST1/input_weekly_2024-04-01.feather
    outputs:
      highly_sensitive:
        cohort: output/01HW38MAP18PWK35KP7T46DST1/input_weekly_2024-04-01.feather

  generate_study_population_01HW38MAP18PWK35KP7T46DST1:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --index-date-range="2019-09-01 to 2024-03-31 by month"
      --output-dir=output/01HW38MAP18PWK35KP7T46DST1
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01HW38MAP18PWK35KP7T46DST1/input_*.feather

  join_cohorts_01HW38MAP18PWK35KP7T46DST1:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01HW38MAP18PWK35KP7T46DST1/input_20*.feather
        --rhs output/01HW38MAP18PWK35KP7T46DST1/input_ethnicity.feather
        --output-dir output/01HW38MAP18PWK35KP7T46DST1/joined
    needs: [generate_study_population_01HW38MAP18PWK35KP7T46DST1, generate_study_population_ethnicity_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      highly_sensitive:
        cohort: output/01HW38MAP18PWK35KP7T46DST1/joined/input_20*.feather

  generate_measures_01HW38MAP18PWK35KP7T46DST1:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01HW38MAP18PWK35KP7T46DST1/joined"
        --output-dir="output/01HW38MAP18PWK35KP7T46DST1"

    needs: [join_cohorts_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      moderately_sensitive:
        measure: output/01HW38MAP18PWK35KP7T46DST1/measure_all.csv
        decile_measure: output/01HW38MAP18PWK35KP7T46DST1/measure_practice_rate_deciles.csv

  top_5_table_01HW38MAP18PWK35KP7T46DST1:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01HW38MAP18PWK35KP7T46DST1"
    needs: [generate_measures_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      moderately_sensitive:
        table_1: output/01HW38MAP18PWK35KP7T46DST1/top_5_code_table_1.csv
        table_2: output/01HW38MAP18PWK35KP7T46DST1/top_5_code_table_2.csv
        tables_for_checking: output/01HW38MAP18PWK35KP7T46DST1/for_checking/top_5*.csv

  plot_measure_01HW38MAP18PWK35KP7T46DST1:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir output/01HW38MAP18PWK35KP7T46DST1
        --output-dir output/01HW38MAP18PWK35KP7T46DST1
    needs: [generate_measures_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      moderately_sensitive:
        measure: output/01HW38MAP18PWK35KP7T46DST1/plot_measure*.png
        data: output/01HW38MAP18PWK35KP7T46DST1/for_checking/plot_measure_for_checking.csv
        deciles: output/01HW38MAP18PWK35KP7T46DST1/deciles_chart.png

  event_counts_01HW38MAP18PWK35KP7T46DST1:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01HW38MAP18PWK35KP7T46DST1" --output-dir="output/01HW38MAP18PWK35KP7T46DST1"
    needs: [join_cohorts_01HW38MAP18PWK35KP7T46DST1, generate_study_population_weekly_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      moderately_sensitive:
        measure: output/01HW38MAP18PWK35KP7T46DST1/event_counts.json

  generate_report_01HW38MAP18PWK35KP7T46DST1:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01HW38MAP18PWK35KP7T46DST1"
    needs: [event_counts_01HW38MAP18PWK35KP7T46DST1, top_5_table_01HW38MAP18PWK35KP7T46DST1, plot_measure_01HW38MAP18PWK35KP7T46DST1]
    outputs:
      moderately_sensitive:
        notebook: output/01HW38MAP18PWK35KP7T46DST1/report.html