version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GZ17R6MDZHJSDYWR97H9PHV2 --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ17R6MDZHJSDYWR97H9PHV2/input_ethnicity.feather

  generate_study_population_weekly_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="weekly"
      --param time_value="None"
      --param time_ever="True"
      --param time_scale=""
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns=""
      --index-date_range="2023-04-10 to 2023-04-10 by week"
      --output-dir=output/01GZ17R6MDZHJSDYWR97H9PHV2
      --output-format=feather
      --output-file=output/01GZ17R6MDZHJSDYWR97H9PHV2/input_weekly_2023-04-10.feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ17R6MDZHJSDYWR97H9PHV2/input_weekly_2023-04-10.feather

  generate_study_population_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="None"
      --param time_ever="True"
      --param time_scale=""
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age,ethnicity,imd,region"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GZ17R6MDZHJSDYWR97H9PHV2
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ17R6MDZHJSDYWR97H9PHV2/input_*.feather

  join_cohorts_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GZ17R6MDZHJSDYWR97H9PHV2/input_20*.feather
        --rhs output/01GZ17R6MDZHJSDYWR97H9PHV2/input_ethnicity.feather
        --output-dir output/01GZ17R6MDZHJSDYWR97H9PHV2/joined
    needs: [generate_study_population_01GZ17R6MDZHJSDYWR97H9PHV2, generate_study_population_ethnicity_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      highly_sensitive:
        cohort: output/01GZ17R6MDZHJSDYWR97H9PHV2/joined/input_20*.feather

  generate_measures_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01GZ17R6MDZHJSDYWR97H9PHV2/joined"

    needs: [join_cohorts_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      moderately_sensitive:
        measure: output/01GZ17R6MDZHJSDYWR97H9PHV2/joined/measure_all.csv
        decile_measure: output/01GZ17R6MDZHJSDYWR97H9PHV2/joined/measure_practice_rate_deciles.csv

  top_5_table_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GZ17R6MDZHJSDYWR97H9PHV2"
    needs: [generate_measures_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      moderately_sensitive:
        tables: output/01GZ17R6MDZHJSDYWR97H9PHV2/joined/top_5*.csv

  plot_measure_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --output-dir output/01GZ17R6MDZHJSDYWR97H9PHV2
    needs: [generate_measures_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      moderately_sensitive:
        measure: output/01GZ17R6MDZHJSDYWR97H9PHV2/plot_measure*.png
        deciles: output/01GZ17R6MDZHJSDYWR97H9PHV2/deciles_chart.png

  event_counts_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01GZ17R6MDZHJSDYWR97H9PHV2" --output-dir="output/01GZ17R6MDZHJSDYWR97H9PHV2"
    needs: [join_cohorts_01GZ17R6MDZHJSDYWR97H9PHV2, generate_study_population_weekly_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      moderately_sensitive:
        measure: output/01GZ17R6MDZHJSDYWR97H9PHV2/event_counts.json

  generate_report_01GZ17R6MDZHJSDYWR97H9PHV2:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GZ17R6MDZHJSDYWR97H9PHV2"
      --population="adults"
      --breakdowns=sex
      --breakdowns=age
      --breakdowns=ethnicity
      --breakdowns=imd
      --breakdowns=region
      --codelist-1-name="Doxycycline (tetracyclines)"
      --codelist-2-name="Chronic obstructive pulmonary disease (COPD) codes"
      --codelist-1-link="user/alexorlek/doxycycline-tetracyclines/4458c45a"
      --codelist-2-link="nhsd-primary-care-domain-refsets/copd_cod/20210127"
      --time-value="None"
      --time-scale=""
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
      
      --time-ever
      
    needs: [event_counts_01GZ17R6MDZHJSDYWR97H9PHV2, top_5_table_01GZ17R6MDZHJSDYWR97H9PHV2, plot_measure_01GZ17R6MDZHJSDYWR97H9PHV2]
    outputs:
      moderately_sensitive:
        notebook: output/01GZ17R6MDZHJSDYWR97H9PHV2/report.html