version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GZ0S80X6JS205PCHC5NDCZ4R --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0S80X6JS205PCHC5NDCZ4R/input_ethnicity.feather

  generate_study_population_weekly_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="medication"
      --param codelist_1_frequency="weekly"
      --param time_value="0"
      --param time_ever="False"
      --param time_scale="weeks"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns=""
      --index-date_range="2023-04-10 to 2023-04-10 by week"
      --output-dir=output/01GZ0S80X6JS205PCHC5NDCZ4R
      --output-format=feather
      --output-file=output/01GZ0S80X6JS205PCHC5NDCZ4R/input_weekly_2023-04-10.feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0S80X6JS205PCHC5NDCZ4R/input_weekly_2023-04-10.feather

  generate_study_population_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="medication"
      --param codelist_1_frequency="monthly"
      --param time_value="0"
      --param time_ever="False"
      --param time_scale="weeks"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age,ethnicity,imd,region"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GZ0S80X6JS205PCHC5NDCZ4R
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0S80X6JS205PCHC5NDCZ4R/input_*.feather

  join_cohorts_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GZ0S80X6JS205PCHC5NDCZ4R/input_20*.feather
        --rhs output/01GZ0S80X6JS205PCHC5NDCZ4R/input_ethnicity.feather
        --output-dir output/01GZ0S80X6JS205PCHC5NDCZ4R/joined
    needs: [generate_study_population_01GZ0S80X6JS205PCHC5NDCZ4R, generate_study_population_ethnicity_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      highly_sensitive:
        cohort: output/01GZ0S80X6JS205PCHC5NDCZ4R/joined/input_20*.feather

  generate_measures_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01GZ0S80X6JS205PCHC5NDCZ4R/joined"

    needs: [join_cohorts_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0S80X6JS205PCHC5NDCZ4R/joined/measure_all.csv
        decile_measure: output/01GZ0S80X6JS205PCHC5NDCZ4R/joined/measure_practice_rate_deciles.csv

  top_5_table_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GZ0S80X6JS205PCHC5NDCZ4R"
    needs: [generate_measures_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      moderately_sensitive:
        tables: output/01GZ0S80X6JS205PCHC5NDCZ4R/joined/top_5*.csv

  plot_measure_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --output-dir output/01GZ0S80X6JS205PCHC5NDCZ4R
    needs: [generate_measures_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0S80X6JS205PCHC5NDCZ4R/plot_measure*.png
        deciles: output/01GZ0S80X6JS205PCHC5NDCZ4R/deciles_chart.png

  event_counts_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01GZ0S80X6JS205PCHC5NDCZ4R" --output-dir="output/01GZ0S80X6JS205PCHC5NDCZ4R"
    needs: [join_cohorts_01GZ0S80X6JS205PCHC5NDCZ4R, generate_study_population_weekly_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0S80X6JS205PCHC5NDCZ4R/event_counts.json

  generate_report_01GZ0S80X6JS205PCHC5NDCZ4R:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GZ0S80X6JS205PCHC5NDCZ4R"
      --population="adults"
      --breakdowns=sex
      --breakdowns=age
      --breakdowns=ethnicity
      --breakdowns=imd
      --breakdowns=region
      --codelist-1-name="Oral prednisolone codes"
      --codelist-2-name="Doxycycline (tetracyclines)"
      --codelist-1-link="primis-covid19-vacc-uptake/astrxm2/v1.5.3"
      --codelist-2-link="user/alexorlek/doxycycline-tetracyclines/4458c45a"
      --time-value="0"
      --time-scale="weeks"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
      
    needs: [event_counts_01GZ0S80X6JS205PCHC5NDCZ4R, top_5_table_01GZ0S80X6JS205PCHC5NDCZ4R, plot_measure_01GZ0S80X6JS205PCHC5NDCZ4R]
    outputs:
      moderately_sensitive:
        notebook: output/01GZ0S80X6JS205PCHC5NDCZ4R/report.html